### ISSUE TITLE
Travis" failing

### ISSUE THREAD

**Issue by moesaeed** [fidelisa/flutter_plugins#1]
Hello, 
In the home page of this repo, you can notice that "Travis" failing. 

Please notice the attached file.

<img width="488" alt="screen shot 2018-04-20 at 10 02 04 am" src="https://user-images.githubusercontent.com/2155564/39035262-0bfdb158-4482-11e8-88d2-2d58b40bc31f.png">

**Comment by ypelud** [comment]
Hy,
Thanks it's fixed now.
