### ISSUE TITLE
Flutter Firebase Animated List Not Updating 

### ISSUE THREAD

**Issue by bdytx5** [fidelisa/flutter_plugins#12]
I have a stateful widget, with a FirebaseAnimatedList inside the build method. If there is initially no data retrieved from the Query, and I add data after the initial build method, the list does not update to show the data. If I dismiss the page, and come back after adding the data, it will show up just fine. I've set up break points inside the animated list, and it will partially rebuild when I add the data, but it will not get to the point where it returns the widget. Is this a bug or expected behavior?

**Comment by ypelud** [comment]
maybe you're wrong repository because I do not understand the problem

**Comment by bdytx5** [comment]
What part doesn't make sense?

https://pub.dartlang.org/packages/flutter_firebase_ui
