### ISSUE TITLE
use the translation 

### ISSUE THREAD

**Issue by LucasParsy** [fidelisa/flutter_plugins#14]
I see you made a french and German localization of this library, but I can't find how to use it.
I set my locale to french in my app, I can get strings in french with `MaterialLocalizations.of(context)` ,
but the `SignInScreen` is still in english.

my code for setting up the localization:

```dart
@override
  Widget build(BuildContext context) {
    return new MaterialApp(
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: [
        const Locale('fr', 'fr')
]
...
)
```

I figured I could manually edit the library default locale, but I would like the lib to adapt to the device locale.

thank you for your help!

**Comment by ypelud** [comment]
You have forgot the localization delegate (FFULocalizations), try this:

```dart
localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        FFULocalizations.delegate,
      ],
```

**Comment by LucasParsy** [comment]
thank you very much!
I will try to contribute to your project, I already submitted a small pull request.
