### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by ScholliYT** [fidelisa/flutter_plugins#6]
When I try to run the example for flutter_firebase_ui I keep getting into this error:

> PlatformException(sign_in_failed, Status{statusCode=DEVELOPER_ERROR, resolution=null}, null)

in: flutter\packages\flutter\lib\src\services\message_codecs.dart

Steps to reproduce:
- Open example for flutter_firebase_ui
- Run on android device with debugger enabled
- try to login with a google account

**Comment by ypelud** [comment]
Seems to be like this : https://stackoverflow.com/questions/37273145/error-statusstatuscode-developer-error-resolution-null

I fix it in the example sources

**Comment by ScholliYT** [comment]
Now it's working for me 👍 Thanks
