### ISSUE TITLE
Adding flutter_firebase_ui: "^0.0.4" to dependencies will crash my app.

### ISSUE THREAD

**Issue by amlbar** [fidelisa/flutter_plugins#7]
Running the example works fine but when setting up my app and add flutter_firebase_ui: "^0.0.4" to pubspec.yaml will crash the app (http://take.ms/mXM5E). Even just adding the hello world sample code in my main.dart, the app will still crash. Is there anything missing here or this is a bug?

**Comment by ypelud** [comment]
did you follow the configuration indications as describe [here](https://pub.dartlang.org/packages/firebase_auth)
I think something is missing (Facebook or Google Ids)

**Comment by amlbar** [comment]
I did follow the Android integration to configure my Gradle and found out that firebase_auth is causing the app to stop.

**Comment by ypelud** [comment]
Does it work now ?

**Comment by amlbar** [comment]
I already did it before I created this issue. I will get back soon on this and will try again. Maybe it will work this time.
