### ISSUE TITLE
Better UI

### ISSUE THREAD

**Issue by joostlek** [fidelisa/flutter_plugins#9]
![image](https://user-images.githubusercontent.com/7083755/42222317-2280c720-7ed5-11e8-8e3f-b9310ad8649f.png)

I made an UI which is looking more like the native Firebase Auth UI. Can we maybe colaborate on this, and create something nice?

It's in https://github.com/joostlek/Eros

**Comment by ypelud** [comment]
I improve UI based on yours, thanks!
